<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="INSERT.PHP" method="post">
        <lable>Email:</lable><input type="email" name="email"><br>

        <lable>NAME:</lable><input type="text" name="name"><br>

        <lable>ROLL NUMBER:</lable><input type="text" name="roll_number"><br>

        <lable>DEPARTMENT:</lable><input type="text" name="department"><br>

        <lable>SHIFT:</lable><input type="text" name="shift"><br>
        
        <lable>DESCRIPTION:</lable><input type="text" name="description"><br>

        <button name="submit">Submit</button>
        
    </form>
</body>
</html>